### ISSUE TITLE
SSL Authentication problems in AQT simulators

### ISSUE THREAD

**Issue by GSiddiMoreau** [qiskit-community/qiskit-aqt-provider#59]
### Informations

- **Qiskit AQT Provider version**: 0.4.3
- **Python version**: 3.10
- **Operating system**: linux

### What is the current behavior?
When I try to utilize the simulator via qiskit, embedding it in a vqe workflow embedded in a GroundStateEigensolver (see qiskit-nature workflows), if I insert as API token the primary key provided in the profile page of https://gateway-portal.aqt.eu/developer, the job fails with
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED+ certificate verify failed: self signed certificate (_ssl.c:997)

How am I supposed to define ssl primary and secondary keys in the qiskit_aqt_provider framework? and most of all, is the primary key supposed to be the API token?

### Steps to reproduce the problem

mytoken='primary_string_from_aqt_cloud_profile'
from qiskit_aqt_provider import AQTProvider
aqt = AQTProvider(mytoken)
backend=aqt.backends.aqt_qasm_simulator_noise_1
from qiskit.primitives import BackendEstimator
mapper=JordanWignerMapper()
myest=BackendEstimator(backend=backend)
vqe=VQEUCCFactory(myest, UCCSD(), SLSQP())
calc=GroundStateEigensolver(mapper, vqe_solver)
res=calc.solve(problem)

### What is the expected behavior?
the expected behaviour is that the vqe workflows addresses circuit evaluations to the selected backend, with no authentication errors.

**Comment by fg-aqt** [comment]
This issue is closed because recent updates of the qiskit-aqt-provider render the problem irrelevant. 

Due to a significant change of the AQT APIs, the services available through [https://gateway-portal.aqt.eu](https://gateway-portal.aqt.eu) are being discontinued since June 2023!

The option of sending circuits to a hosted simulator is replaced by offline simulation capabilities of the current qiskit-aqt-provider:
- based on Qiskit Aer
- with an optional noise model simulating AQT backends
- same restrictions as on real hardware
- switch from offline simulation to processing on AQT QC hardware via cloud access is straight-forward
- runs on your own classical hardware

For further information check out https://www.aqt.eu/qc-system and the [qiskit-aqt-provider user guide](https://qiskit-community.github.io/qiskit-aqt-provider/guide.html)
