### ISSUE TITLE
Start deploying the documentation in a GitHub page

### ISSUE THREAD

**Issue by 1ucian0** [qiskit-community/qiskit-aqt-provider#60]
Hello there! With the sunset of the Qiskit Partner program, consider start deploying the documentation in https://qiskit-community.github.io/qiskit-aqt-provider .  The documentation currently deploys in https://qiskit.org/ecosystem/aqt/, and qiskit.org can provide redirects.

Let me know if you need help from a qiskit-community admin. 

Thank you!

**Comment by fg-aqt** [comment]
> Hello there! With the sunset of the Qiskit Partner program, consider start deploying the documentation in https://qiskit-community.github.io/qiskit-aqt-provider . The documentation currently deploys in https://qiskit.org/ecosystem/aqt/, and qiskit.org can provide redirects.

We followed your advise and deploy the documentation now under https://qiskit-community.github.io/qiskit-aqt-provider/

> Let me know if you need help from a qiskit-community admin.

Your help would be very much appreciated, to be more specific:
1. Would it be possible to redirect to the new documentation from https://qiskit.org/ecosystem/aqt/ ?
2. We noticed that searching for "AQT" on https://qiskit.org/ecosystem does not return any results. What can we do so that the Qiskit AQT Provider can be found there?
