### ISSUE TITLE
More than one backend matches the criteria

### ISSUE THREAD

**Issue by fg-aqt** [qiskit-community/qiskit-aqt-provider#84]
### Informations

- **Qiskit AQT Provider version**: v0.18.0
- **Python version**: 3.11.3
- **Operating system**: Ubuntu

### What is the current behavior?

The `ProviderV1.get_backend` function throws `qiskit.providers.exceptions.QiskitBackendNotFoundError: 'More than one backend matches the criteria'` if a workspace name is a prefix of another workspace name and the device to be used is present in both workspaces. In case the other workspace is used, it does not throw this error and works as expected. 

### Steps to reproduce the problem

1. Create two workspaces `foo` and `foo_bar` with a common resource e.g. `qc`
2. Make sure to use a token which enables access to both workspaces
3. run 
```
aqt = AQTProvider("token")
backend = aqt.get_backend(name="qc", workspace="foo")
```

### What is the expected behavior?

If the combination of parameters `name` and `workspace` is unique this error should not be produced

**Comment by airwoodix** [comment]
The values passed to the `AQTProvider.get_backend()` (and `AQTProvider.backends()`) arguments actually are patterns, so this is the expected behavior. You can get the wanted behavior by terminating the pattern:

```python
aqt.get_backend(name="qc", workspace="foo$")
```

will not match `foo_bar/qc` and return the one targeted backend.

I see that this behavior is a bit surprising. We could:

1. emphasize this in the user guide (it is already explicit in the [docstring](https://github.com/qiskit-community/qiskit-aqt-provider/blob/35459ee64ea3d1f41751d27d9687c9b355c0b4d0/qiskit_aqt_provider/aqt_provider.py#L214));
2. only use the argument as pattern if it is a compiled pattern (i.e. `re.compile(...)`) and do an exact match (string comparison) otherwise;
3. drop the whole pattern matching feature and do only exact matches, which is probably more what is expected with such an API.

**Comment by fg-aqt** [comment]
If there is no specific reason for using pattern matching, I would go for option 3 as it seems to be the most intuitive for users.
